VirtoCommerce.CatalogCsvImportModule.Web/Controllers/Api/CatalogModuleExportImportController.cs
VirtoCommerce.CatalogCsvImportModule.Web/Scripts/blades/import/wizard/catalog-CSV-import-wizard.js

Issue when tab or space are delimiters

---

VirtoCommerce.CatalogCsvImportModule.Web/Controllers/Api/CatalogModuleExportImportController.cs
VirtoCommerce.CatalogCsvImportModule.Web/module.manifest

dev 602 Add file name template

---

src/VirtoCommerce.CatalogCsvImportModule.Core/Model/CsvProduct.cs

VP-2259 Fix category Path

---

src/VirtoCommerce.CatalogCsvImportModule.Core/VirtoCommerce.CatalogCsvImportModule.Core.csproj
src/VirtoCommerce.CatalogCsvImportModule.Data/VirtoCommerce.CatalogCsvImportModule.Data.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/Controllers/Api/CatalogModuleExportImportController.cs
src/VirtoCommerce.CatalogCsvImportModule.Web/VirtoCommerce.CatalogCsvImportModule.Web.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/module.manifest
tests/VirtoCommerce.CatalogCsvImportModule.Test/VirtoCommerce.CatalogCsvImportModule.Test.csproj

Increase dependency package version
Fix lost error message

VP-2390 Fix broken export

---

src/VirtoCommerce.CatalogCsvImportModule.Web/Controllers/Api/CatalogModuleExportImportController.cs
src/VirtoCommerce.CatalogCsvImportModule.Web/Model/PushNotifications/JobNotificationBase.cs

VP-2309: Make ErrorCount computable

---

src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs

VP-2258 Fix category search depth

---

src/VirtoCommerce.CatalogCsvImportModule.Web/module.manifest

VP-2258: Update dependency version

---

src/VirtoCommerce.CatalogCsvImportModule.Core/Model/CsvProduct.cs

VP-3583: Import multiple product images via CSV

---

src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs

VP-5698 Product import CSV > Some Description cleared or empty created
update condition

VP-5698: Fix empty created description 

---

src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs

Remove empty reviews (descriptions )

VP-5878: Fix product have one empty description after import

---

src/VirtoCommerce.CatalogCsvImportModule.Web/Scripts/blades/import/wizard/catalog-CSV-import-wizard.tpl.html

VP-6770: Replace panel action icons

---

src/VirtoCommerce.CatalogCsvImportModule.Web/Scripts/blades/export/catalog-CSV-export.js

VP-7045: Icons broken on several pages

---

src/VirtoCommerce.CatalogCsvImportModule.Core/ModuleConstants.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs

https://virtocommerce.atlassian.net/browse/VP-6784

VP-6784: Fix name for CreateDictionaryValues setting

---

src/VirtoCommerce.CatalogCsvImportModule.Core/VirtoCommerce.CatalogCsvImportModule.Core.csproj
src/VirtoCommerce.CatalogCsvImportModule.Data/VirtoCommerce.CatalogCsvImportModule.Data.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-207

PT-207: Enable Source link support

---

src/VirtoCommerce.CatalogCsvImportModule.Web/Scripts/blades/import/wizard/catalog-CSV-import-wizard.js
src/VirtoCommerce.CatalogCsvImportModule.Web/Scripts/virtoCommerce.catalogCsvImportModule.js

Reverts VirtoCommerce/vc-module-catalog-csv-import#77

Revert "PT-1526: Fix templates URIs"

---

src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs

PT-2375: Fix products import with space delimiter

---

README.md
src/VirtoCommerce.CatalogCsvImportModule.Core/Model/CsvProduct.cs
src/VirtoCommerce.CatalogCsvImportModule.Core/Model/CsvProductMappingConfiguration.cs
src/VirtoCommerce.CatalogCsvImportModule.Core/Model/CsvSeoInfo.cs
tests/VirtoCommerce.CatalogCsvImportModule.Test/MappingTests.cs
tests/VirtoCommerce.CatalogCsvImportModule.Test/data/product-productproperties-seoInfo.csv

Added SEO Meta Keywords and Image Alternative text to export import

PT-2998 Add missing Seo fields to mapping

---

src/VirtoCommerce.CatalogCsvImportModule.Core/Model/CsvProduct.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs

PT-820: Add more validations during import

---

src/VirtoCommerce.CatalogCsvImportModule.Core/VirtoCommerce.CatalogCsvImportModule.Core.csproj
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogExporter.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvProductMap.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/VirtoCommerce.CatalogCsvImportModule.Data.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/Controllers/Api/CatalogModuleExportImportController.cs
src/VirtoCommerce.CatalogCsvImportModule.Web/Localizations/de.VirtoCommerce.CatalogCsvImportModule.json
src/VirtoCommerce.CatalogCsvImportModule.Web/Localizations/en.VirtoCommerce.CatalogCsvImportModule.json
src/VirtoCommerce.CatalogCsvImportModule.Web/Localizations/ru.VirtoCommerce.CatalogCsvImportModule.json
src/VirtoCommerce.CatalogCsvImportModule.Web/Scripts/blades/import/wizard/catalog-CSV-import-wizard.js
src/VirtoCommerce.CatalogCsvImportModule.Web/VirtoCommerce.CatalogCsvImportModule.Web.csproj
tests/VirtoCommerce.CatalogCsvImportModule.Test/MappingTests.cs
tests/VirtoCommerce.CatalogCsvImportModule.Test/VirtoCommerce.CatalogCsvImportModule.Tests.csproj

Update CsvHelper nuget package to latest versions
https://virtocommerce.atlassian.net/browse/PT-3918

PT-3918: Update CsvHelper nuget package to latest versions

---

.github/workflows/main.yml
.github/workflows/publish_nugets.yml
Directory.Build.props
src/VirtoCommerce.CatalogCsvImportModule.Core/VirtoCommerce.CatalogCsvImportModule.Core.csproj
src/VirtoCommerce.CatalogCsvImportModule.Data/VirtoCommerce.CatalogCsvImportModule.Data.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/VirtoCommerce.CatalogCsvImportModule.Web.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/module.manifest
tests/VirtoCommerce.CatalogCsvImportModule.Test/VirtoCommerce.CatalogCsvImportModule.Tests.csproj

Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956

PT-1956: Bump .Net and EF up to 6

---

src/VirtoCommerce.CatalogCsvImportModule.Core/VirtoCommerce.CatalogCsvImportModule.Core.csproj
src/VirtoCommerce.CatalogCsvImportModule.Data/VirtoCommerce.CatalogCsvImportModule.Data.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/VirtoCommerce.CatalogCsvImportModule.Web.csproj

https://virtocommerce.atlassian.net/browse/PT-6404

PT-6404: Fix empty sonar codecoverage report

---

src/VirtoCommerce.CatalogCsvImportModule.Core/Model/CsvProduct.cs
src/VirtoCommerce.CatalogCsvImportModule.Web/module.manifest

Jira-link:
https://virtocommerce.atlassian.net/browse/VP-8014
Artifact URL: https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogCsvImportModule_3.201.0-pr-93.zip

Fixed Null Reference error if list of fulfillment centers is empty

---

VirtoCommerce.CatalogCsvImportModule.sln
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs

fix: Fulfillment Center amount to 0 it does not get updated
https://virtocommerce.atlassian.net/browse/PT-9349

PT-9349: Fulfillment Center amount to 0 it does not get updated

---

src/VirtoCommerce.CatalogCsvImportModule.Web/package-lock.json
src/VirtoCommerce.CatalogCsvImportModule.Web/package.json
src/VirtoCommerce.CatalogCsvImportModule.Web/webpack.config.js

feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395

PT-9395: add nodejs-lts support

---

Directory.Build.props
src/VirtoCommerce.CatalogCsvImportModule.Core/VirtoCommerce.CatalogCsvImportModule.Core.csproj
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/VirtoCommerce.CatalogCsvImportModule.Data.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/VirtoCommerce.CatalogCsvImportModule.Web.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/module.manifest
src/VirtoCommerce.CatalogCsvImportModule.Web/package-lock.json
tests/VirtoCommerce.CatalogCsvImportModule.Test/ImporterTests.cs
tests/VirtoCommerce.CatalogCsvImportModule.Test/MergingTests.cs
tests/VirtoCommerce.CatalogCsvImportModule.Test/VirtoCommerce.CatalogCsvImportModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogCsvImportModule_3.800.0-pr-107-2095.zip

PT-14740: .net 8

---

src/VirtoCommerce.CatalogCsvImportModule.Data/VirtoCommerce.CatalogCsvImportModule.Data.csproj
src/VirtoCommerce.CatalogCsvImportModule.Web/Scripts/blades/export/catalog-CSV-export.js
src/VirtoCommerce.CatalogCsvImportModule.Web/Scripts/blades/export/catalog-CSV-export.tpl.html

https://virtocommerce.atlassian.net/browse/VCST-2374
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogCsvImportModule_3.803.0-pr-109-6b53.zip

VCST-2401: use ui-scrol-drop-down on csv export blade

---

README.md

Direct link to docs 
https://docs.virtocommerce.org/platform/user-guide/catalog-csv-export-import/overview/

Direct link to docs

---

VirtoCommerce.CatalogCsvImportModule.sln.DotSettings
src/VirtoCommerce.CatalogCsvImportModule.Core/Extensions/AsyncEnumerableExtensions.cs
src/VirtoCommerce.CatalogCsvImportModule.Core/Extensions/InventorySearchServiceExtensions.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogExporter.cs

fix: Introduce _batchSize constant for batch processing of product IDs. Process product IDs in chunks using FetchThere for each batch. Update fetching logic to use a while loop with break condition.
https://virtocommerce.atlassian.net/browse/VCST-2576
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogCsvImportModule_3.806.0-pr-112-6d8c.zip

VCST-2576: Optimize product export with batch processing

---

src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvCatalogImporter.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvProductMap.cs
src/VirtoCommerce.CatalogCsvImportModule.Data/Services/CsvReaderExtension.cs
tests/VirtoCommerce.CatalogCsvImportModule.Test/ImporterTests.cs
tests/VirtoCommerce.CatalogCsvImportModule.Test/MappingTests.cs

https://virtocommerce.atlassian.net/browse/VCST-3452
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogCsvImportModule_3.810.0-pr-119-a523.zip

VCST-3452: Fix multilanguage properties
